version: "3.8"

services:
  mariadb:
    container_name: suggestclasses-mariadb
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$DATABASE_NAME
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - MYSQL_HOST=$DATABASE_HOST
    restart: always
  web:
    container_name: suggestclasses-server
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
