version: "3.8"

services:
  web:
    container_name: suggestclasses-web
    image: suggestclasses:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput
             python manage.py migrate --noinput
             export DJANGO_SUPERUSER_PASSWORD=admin
             export DJANGO_SUPERUSER_USERNAME=admin
             export DJANGO_SUPERUSER_EMAIL=labensufrn@gmail.com
             python manage.py createsuperuser --noinput
             python manage.py runserver 0.0.0.0:8003"
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    external_links:
      - postgres-server:postgres-server

networks:
  default:
    external: true
    name: labens-network